FROM node:22-alpine

WORKDIR /app

COPY package.json pnpm-lock.yaml vite.config.js ./
RUN npm install -g pnpm && pnpm install

COPY . .

EXPOSE 5173

CMD ["pnpm", "run", "dev", "--host", "0.0.0.0", "--port", "5173"]
